In [1]:
import tensorflow as tf

2023-05-13 10:11:54.411018: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-13 10:11:54.453779: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-13 10:11:54.454372: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-13 10:11:55.283093: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.13403106], shape=(1,), dtype=float32)
tf.Tensor([0.38594615], shape=(1,), dtype=float32)


In [3]:
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.6717944], shape=(1,), dtype=float32)
tf.Tensor([0.00298703], shape=(1,), dtype=float32)


In [4]:
tf.random.set_seed(1234)  # Global level seed
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

# Se a semente de nivel global for definida os valores dos tensors serão os mesmos sempre que o programa for 
# executado, mas não serão iguais entre si, pois cada tensor usa uma semente a NÍVEL DE OPERAÇÃO aleatória e diferente

tf.random.set_seed(None)

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [5]:
print(tf.random.uniform([1], seed=1))
print(tf.random.uniform([1], seed=1))

tf.Tensor([0.2390374], shape=(1,), dtype=float32)
tf.Tensor([0.22267115], shape=(1,), dtype=float32)


In [10]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))
print(tf.random.uniform([1], seed=1))
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))
print(tf.random.uniform([1], seed=1))

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [14]:
tf.random.set_seed(4029)

tensor1 = tf.random.uniform(shape=(2,2), seed=7)
tensor2 = tf.random.uniform(shape=(2,2), seed=7)
tensor3 = tf.random.uniform(shape=(2,2), seed=7)
tensor4 = tf.random.uniform(shape=(2,2), seed=7)
tensor5 = tf.random.uniform(shape=(2,2), seed=7)

tensor1, tensor2, tensor3, tensor4, tensor5

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.17115712, 0.6531501 ],
        [0.8587817 , 0.874786  ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.7144613 , 0.37347782],
        [0.641343  , 0.10519004]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.2770716 , 0.5369843 ],
        [0.34588027, 0.60669184]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.5720482 , 0.18713129],
        [0.19723058, 0.462242  ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0.2036438 , 0.44336116],
        [0.07702982, 0.71694434]], dtype=float32)>)