In [1]:
import tensorflow as tf

2023-05-22 00:33:00.255505: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-22 00:33:00.499006: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-22 00:33:00.501834: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-22 00:33:01.680821: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


### 1.Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [2]:
scalar = tf.constant(7)

In [3]:
vector = tf.constant([1, 2, 3, 5, 7])

In [4]:
matrix = tf.constant([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 10]])

### 2.Find the shape, rank and size of the tensors you created in 1.

In [5]:
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [6]:
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([5]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=5>)

In [7]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 5]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=10>)

### 3.Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [19]:
tensor1 = tf.random.uniform(shape=[5, 300])
tensor2 = tf.random.uniform(shape=[5, 300])

tensor1, tensor2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.8444767 , 0.7578974 , 0.34038627, ..., 0.35887814, 0.38241577,
         0.80872214],
        [0.3795607 , 0.37561512, 0.27849054, ..., 0.19836926, 0.57988   ,
         0.9570756 ],
        [0.9875188 , 0.24338913, 0.5670984 , ..., 0.7764636 , 0.4196025 ,
         0.5700418 ],
        [0.98231256, 0.5920191 , 0.85951495, ..., 0.12874973, 0.707363  ,
         0.5642314 ],
        [0.05201101, 0.36552262, 0.79726887, ..., 0.17237341, 0.47779226,
         0.38167906]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.12139845, 0.5254301 , 0.99748254, ..., 0.82572305, 0.021312  ,
         0.04565167],
        [0.9042978 , 0.18028367, 0.34447443, ..., 0.48597753, 0.20713747,
         0.37397707],
        [0.439296  , 0.7932527 , 0.8485379 , ..., 0.27898908, 0.01610732,
         0.22265244],
        [0.36575723, 0.77265775, 0.16068089, ..., 0.9003936 , 0.5801039 ,
         0.60614145],
        [0.43772

### 4.Multiply the two tensors you created in 3 using matrix multiplication.

In [20]:
tensor1 * tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.10251816, 0.3982221 , 0.33952937, ..., 0.29633394, 0.00815004,
        0.03691952],
       [0.34323594, 0.06771727, 0.09593287, ..., 0.096403  , 0.12011487,
        0.3579243 ],
       [0.43381307, 0.19306909, 0.48120448, ..., 0.21662487, 0.00675867,
        0.12692119],
       [0.35928792, 0.45742813, 0.13810763, ..., 0.11592543, 0.41034403,
        0.34200403],
       [0.02276628, 0.12441191, 0.1391964 , ..., 0.05149574, 0.09781797,
        0.12304203]], dtype=float32)>

### 5.Multiply the two tensors you created in 3 using dot product.

In [26]:
tf.tensordot(tensor1, tf.transpose(tensor2), axes=0)

<tf.Tensor: shape=(5, 300, 300, 5), dtype=float32, numpy=
array([[[[1.02518164e-01, 7.63658464e-01, 3.70975256e-01,
          3.08873445e-01, 3.69644582e-01],
         [4.43713456e-01, 1.52245358e-01, 6.69883430e-01,
          6.52491450e-01, 2.87432164e-01],
         [8.42350781e-01, 2.90900648e-01, 7.16570497e-01,
          1.35691270e-01, 1.47438481e-01],
         ...,
         [6.97303891e-01, 4.10396695e-01, 2.35599771e-01,
          7.60361433e-01, 2.52283424e-01],
         [1.79974865e-02, 1.74922764e-01, 1.36022568e-02,
          4.89884198e-01, 1.72888935e-01],
         [3.85517739e-02, 3.15814912e-01, 1.88024789e-01,
          5.11872351e-01, 2.72234291e-01]],

        [[9.20075625e-02, 6.85364962e-01, 3.32941294e-01,
          2.77206451e-01, 3.31747055e-01],
         [3.98222089e-01, 1.36636510e-01, 6.01204157e-01,
          5.85595310e-01, 2.57963419e-01],
         [7.55989373e-01, 2.61076272e-01, 6.43104672e-01,
          1.21779628e-01, 1.32322475e-01],
         ...,
   

In [27]:
tf.tensordot(tensor1, tf.transpose(tensor2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[78.66501 , 81.0572  , 77.40768 , 82.372574, 81.18328 ],
       [76.0376  , 78.83511 , 77.03962 , 82.133995, 77.55181 ],
       [72.78781 , 73.438805, 70.018555, 75.912384, 73.50305 ],
       [79.29413 , 78.56099 , 72.4432  , 82.14926 , 76.16867 ],
       [74.18422 , 73.837135, 69.94595 , 71.80888 , 71.758514]],
      dtype=float32)>

In [28]:
tf.tensordot(tf.transpose(tensor1), tensor2, axes=0)

<tf.Tensor: shape=(300, 5, 5, 300), dtype=float32, numpy=
array([[[[1.02518164e-01, 4.43713456e-01, 8.42350781e-01, ...,
          6.97303891e-01, 1.79974865e-02, 3.85517739e-02],
         [7.63658464e-01, 1.52245358e-01, 2.90900648e-01, ...,
          4.10396695e-01, 1.74922764e-01, 3.15814912e-01],
         [3.70975256e-01, 6.69883430e-01, 7.16570497e-01, ...,
          2.35599771e-01, 1.36022568e-02, 1.88024789e-01],
         [3.08873445e-01, 6.52491450e-01, 1.35691270e-01, ...,
          7.60361433e-01, 4.89884198e-01, 5.11872351e-01],
         [3.69644582e-01, 2.87432164e-01, 1.47438481e-01, ...,
          2.52283424e-01, 1.72888935e-01, 2.72234291e-01]],

        [[4.60780822e-02, 1.99432611e-01, 3.78605187e-01, ...,
          3.13412040e-01, 8.08919687e-03, 1.73275825e-02],
         [3.43235940e-01, 6.84285983e-02, 1.30748957e-01, ...,
          1.84457973e-01, 7.86212459e-02, 1.41947001e-01],
         [1.66739509e-01, 3.01087558e-01, 3.22071642e-01, ...,
          1.05893292e-0

In [29]:
tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.2616214 , 2.0721881 , 1.9779664 , ..., 2.0572746 , 0.6930165 ,
        1.0125594 ],
       [0.91512734, 1.2408485 , 1.2508473 , ..., 1.5185052 , 0.5161423 ,
        0.70594287],
       [1.2056394 , 1.6143839 , 1.1939708 , ..., 1.5867013 , 0.7359066 ,
        1.0239576 ],
       ...,
       [0.686592  , 0.99840975, 1.1359493 , ..., 0.776783  , 0.17122294,
        0.3970591 ],
       [1.223001  , 1.3475008 , 1.1343337 , ..., 1.4942861 , 0.64318556,
        0.91053337],
       [1.5875164 , 1.6155281 , 1.7773756 , ..., 1.9139882 , 0.6301172 ,
        0.98681116]], dtype=float32)>

### 6.Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [37]:
tensor3 = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.98830116, 0.70654   , 0.14598262],
        [0.8430643 , 0.53023756, 0.87682045],
        [0.36060274, 0.24083495, 0.53796697],
        ...,
        [0.63297737, 0.62320817, 0.5468799 ],
        [0.05509996, 0.08282292, 0.36342835],
        [0.74299574, 0.4575212 , 0.09702349]],

       [[0.3341974 , 0.17594361, 0.8818613 ],
        [0.10605562, 0.9155023 , 0.5599265 ],
        [0.49738932, 0.80499434, 0.36847734],
        ...,
        [0.15597951, 0.9325092 , 0.97378194],
        [0.21678817, 0.67206585, 0.33939004],
        [0.86368537, 0.88230455, 0.31845796]],

       [[0.10000527, 0.70125365, 0.98486984],
        [0.33217967, 0.04772401, 0.41543925],
        [0.18789959, 0.06245923, 0.2663133 ],
        ...,
        [0.09832931, 0.35285556, 0.30381894],
        [0.5617026 , 0.23092449, 0.53243756],
        [0.98635864, 0.98453   , 0.5538639 ]],

       ...,

       [[0.8088347 , 0.3806821 , 0.3020953 ],
        [0.30

### 7.Find the min and max values of the tensor you created in 6 along the first axis.

In [67]:
tf.reduce_min(tensor3, axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[1.76179409e-03, 1.76072121e-03, 7.62474537e-03],
       [1.79934502e-03, 9.18269157e-04, 5.55694103e-03],
       [6.58392906e-04, 5.45978546e-05, 4.21535969e-03],
       [1.05464458e-03, 1.40696764e-02, 8.85295868e-03],
       [1.55377388e-03, 1.61105394e-02, 8.25166702e-04],
       [2.58171558e-03, 1.44977570e-02, 8.65101814e-04],
       [1.66916847e-03, 2.81774998e-03, 5.30135632e-03],
       [1.90734863e-04, 3.49783897e-03, 2.12514400e-03],
       [1.67528391e-02, 4.14848328e-04, 1.06084347e-03],
       [3.89802456e-03, 6.62434101e-03, 1.42323971e-03],
       [1.97490454e-02, 7.88247585e-03, 1.63960457e-03],
       [2.27832794e-03, 8.98826122e-03, 7.00712204e-04],
       [4.96554375e-03, 2.23088264e-03, 6.41608238e-03],
       [8.33392143e-03, 6.61969185e-04, 8.23736191e-04],
       [9.41240788e-03, 3.34632397e-03, 3.41236591e-03],
       [3.97384167e-03, 2.14290619e-03, 6.72340393e-04],
       [1.38559341e-02, 6.83426857e-04

In [68]:
tf.reduce_max(tensor3, axis=0)

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[0.99947286, 0.9907956 , 0.9997128 ],
       [0.9931247 , 0.99913514, 0.9997767 ],
       [0.99657834, 0.9951482 , 0.9967109 ],
       [0.9919925 , 0.99428916, 0.99841344],
       [0.9976636 , 0.996776  , 0.9997953 ],
       [0.9947995 , 0.9918982 , 0.9986341 ],
       [0.9942652 , 0.99349415, 0.9954276 ],
       [0.999017  , 0.9951087 , 0.9940089 ],
       [0.9995105 , 0.9993249 , 0.99566984],
       [0.98874545, 0.9952309 , 0.99122655],
       [0.9980488 , 0.9942825 , 0.99724627],
       [0.99508   , 0.9945588 , 0.9997647 ],
       [0.99531484, 0.9993284 , 0.992542  ],
       [0.9980025 , 0.9969218 , 0.9999398 ],
       [0.99895763, 0.9997575 , 0.9989648 ],
       [0.9971652 , 0.9999449 , 0.9969053 ],
       [0.99019015, 0.99783504, 0.9992105 ],
       [0.99986553, 0.9932529 , 0.9976289 ],
       [0.994092  , 0.99304295, 0.9913374 ],
       [0.99999046, 0.9973302 , 0.9952872 ],
       [0.99908733, 0.99899197, 0.9898604 ],
     

### 8.Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [72]:
tensor4 = tf.random.uniform(shape=[1, 224, 224, 3])

In [73]:
tf.squeeze(tensor4)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.8917912 , 0.16947746, 0.33910203],
        [0.62121665, 0.40331292, 0.47827244],
        [0.59343123, 0.970327  , 0.95413065],
        ...,
        [0.27960002, 0.81281316, 0.32954073],
        [0.21806657, 0.10556805, 0.9267087 ],
        [0.6185285 , 0.59440625, 0.63664865]],

       [[0.13913071, 0.87584794, 0.614993  ],
        [0.5890312 , 0.9487077 , 0.8912953 ],
        [0.1729573 , 0.559531  , 0.3032186 ],
        ...,
        [0.90214205, 0.24818766, 0.01877046],
        [0.533769  , 0.6495292 , 0.73263884],
        [0.17052639, 0.8345572 , 0.73165965]],

       [[0.549567  , 0.9407909 , 0.5620047 ],
        [0.84173906, 0.35172367, 0.65484273],
        [0.08513594, 0.44135952, 0.41514742],
        ...,
        [0.67116725, 0.564216  , 0.7482203 ],
        [0.26271868, 0.2379235 , 0.47100925],
        [0.67883277, 0.40348125, 0.9419323 ]],

       ...,

       [[0.7083256 , 0.9990572 , 0.68899024],
        [0.04

### 9.Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [79]:
tensor5 = tf.raneg
tensor5

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([33, 54, 23, 57, 28, 11, 25, 86,  9, 34], dtype=int32)>

In [80]:
tensor5[tf.argmax(tensor5)]

<tf.Tensor: shape=(), dtype=int32, numpy=86>

### 10.One-hot encode the tensor you created in 9.

In [81]:
tf.one_hot(tensor5, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>