In [1]:
import numpy as np
import tensorflow as tf

2023-05-19 08:50:11.985432: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-19 08:50:12.027899: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-19 08:50:12.028809: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-19 08:50:12.742662: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


### Axes 

- 0 → Row or height
- 1 → Column or width
- 2 → Deep

![Tensordot exmaple - Medium](https://miro.medium.com/v2/resize:fit:720/format:webp/1*97ZPTZEDXlR0J9WdDpQgJw.png)

x (each instance along axis 1)
y (each instance along axis 0)

In [4]:
x = tf.constant([[1, 2, 3],
                [2, 3 ,4]])
y = tf.constant([[4, 5, 6],
                 [5, 6, 7]])

x, y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[4, 5, 6],
        [5, 6, 7]], dtype=int32)>)

In [5]:
tf.transpose(y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [5, 6],
       [6, 7]], dtype=int32)>

In [8]:
tf.tensordot(x, tf.transpose(y), axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 38],
       [47, 56]], dtype=int32)>

In [9]:
tf.tensordot(x, tf.transpose(y), axes=[[1], [0]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 38],
       [47, 56]], dtype=int32)>

In [10]:
tf.tensordot(x, tf.transpose(y), axes=0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[ 4,  5],
         [ 5,  6],
         [ 6,  7]],

        [[ 8, 10],
         [10, 12],
         [12, 14]],

        [[12, 15],
         [15, 18],
         [18, 21]]],


       [[[ 8, 10],
         [10, 12],
         [12, 14]],

        [[12, 15],
         [15, 18],
         [18, 21]],

        [[16, 20],
         [20, 24],
         [24, 28]]]], dtype=int32)>

In [11]:
x, tf.transpose(y)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 5],
        [5, 6],
        [6, 7]], dtype=int32)>)

In [19]:
tf.tensordot(x, tf.transpose(y), axes=[[0], [1]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 17, 20],
       [23, 28, 33],
       [32, 39, 46]], dtype=int32)>

In [44]:
print(f'''
x (axes 0) -> {x[:, 0]}
y (axes 1) -> {tf.transpose(y)[0]}

1 * 4 + 2 * 5 = 14
''')


x (axes 0) -> [1 2]
y (axes 1) -> [4 5]

1 * 4 + 2 * 5 = 14



In [47]:
print(1 * 4 + 2 * 5)
print(2 * 4 + 3 * 5)
print(3 * 4 + 4 * 5)

14
23
32


In [49]:
x, tf.transpose(y)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [2, 3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[4, 5],
        [5, 6],
        [6, 7]], dtype=int32)>)

In [48]:
tf.tensordot(x, tf.transpose(y), axes=[[0], [1]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 17, 20],
       [23, 28, 33],
       [32, 39, 46]], dtype=int32)>

In [54]:
x_y_tensordot = tf.constant([
    [1*4 + 2*5, 1*5 + 2*6, 1*6 + 2*7],
    [2*4 + 3*5, 2*5 + 3*6, 2*6 + 3*7],
    [3*4 + 4*5, 3*5 + 4*6, 3*6 + 4*7]
])

x_y_tensordot

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 17, 20],
       [23, 28, 33],
       [32, 39, 46]], dtype=int32)>

In [55]:
x_y_tensordot == tf.tensordot(x, tf.transpose(y), axes=[[0], [1]])

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

[[14, 17, 20] -> 1 column of x * all rows of y <br>
[23, 28, 33] -> 2 column of x * all rows of y <br>
[32, 39, 46]] -> 3 column of x * all rows of y <br>